name: Release new packages

on:
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: fregante/setup-git-user@v2
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching
      - name: cargo login
        run: |-
          echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login
      - name: Install smart release
        run: cargo install cargo-smart-release
      - name: Run smart release
        run: cargo smart-release --no-changelog-preview --allow-fully-generated-changelogs --update-crates-index
